# Generated by Django 4.1.1 on 2022-10-17 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_user', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
